/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.payment;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * PaymentCard
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-01-20T19:20:01.153+01:00[Europe/Belgrade]")
public class PaymentCard {
    @SerializedName("name")
    private String name = null;

    @SerializedName("validTo")
    private String validTo = null;

    @SerializedName("number")
    private String number = null;

    public PaymentCard name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public PaymentCard validTo(String validTo) {
        this.validTo = validTo;
        return this;
    }

    /**
     * Get validTo
     *
     * @return validTo
     **/

    public String getValidTo() {
        return validTo;
    }

    public void setValidTo(String validTo) {
        this.validTo = validTo;
    }

    public PaymentCard number(String number) {
        this.number = number;
        return this;
    }

    /**
     * Get number
     *
     * @return number
     **/

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentCard paymentCard = (PaymentCard) o;
        return Objects.equals(this.name, paymentCard.name) &&
                Objects.equals(this.validTo, paymentCard.validTo) &&
                Objects.equals(this.number, paymentCard.number);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, validTo, number);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PaymentCard {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
