//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 04:33:23 PM CET 
//


package org.bp.accountsubscribing;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for bookMovieSubscriptionResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="bookMovieSubscriptionResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="return" type="{http://accountsubscribing.bp.org/}subscribingInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookMovieSubscriptionResponse", propOrder = {
        "_return"
})
@XmlRootElement(name = "bookMovieSubscriptionResponse", namespace =
        "http://accountsubscribing.bp.org/")
public class BookMovieSubscriptionResponse {

    @XmlElement(name = "return")
    protected SubscribingInfo _return;

    /**
     * Gets the value of the return property.
     *
     * @return possible object is
     * {@link SubscribingInfo }
     */
    public SubscribingInfo getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     *
     * @param value allowed object is
     *              {@link SubscribingInfo }
     */
    public void setReturn(SubscribingInfo value) {
        this._return = value;
    }

}
