//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 04:33:23 PM CET 
//


package org.bp.accountsubscribing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for movieSubscription complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="movieSubscription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" minOccurs="0"/&gt;
 *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" minOccurs="0"/&gt;
 *         &lt;element name="typeAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "movieSubscription", propOrder = {
        "from",
        "to",
        "typeAccount"
})
public class MovieSubscription {

    protected Object from;
    protected Object to;
    protected String typeAccount;

    /**
     * Gets the value of the from property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Object getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setFrom(Object value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Object getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setTo(Object value) {
        this.to = value;
    }

    /**
     * Gets the value of the typeAccount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTypeAccount() {
        return typeAccount;
    }

    /**
     * Sets the value of the typeAccount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTypeAccount(String value) {
        this.typeAccount = value;
    }

}
