//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 04:33:23 PM CET 
//


package org.bp.accountsubscribing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for movieSubscriptionAccount complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="movieSubscriptionAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="movieSubscription" type="{http://accountsubscribing.bp.org/}movieSubscription" minOccurs="0"/&gt;
 *         &lt;element name="person" type="{http://accountsubscribing.bp.org/}person" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "movieSubscriptionAccount", propOrder = {
        "movieSubscription",
        "person"
})
public class MovieSubscriptionAccount {

    protected MovieSubscription movieSubscription;
    protected Person person;

    /**
     * Gets the value of the movieSubscription property.
     *
     * @return possible object is
     * {@link MovieSubscription }
     */
    public MovieSubscription getMovieSubscription() {
        return movieSubscription;
    }

    /**
     * Sets the value of the movieSubscription property.
     *
     * @param value allowed object is
     *              {@link MovieSubscription }
     */
    public void setMovieSubscription(MovieSubscription value) {
        this.movieSubscription = value;
    }

    /**
     * Gets the value of the person property.
     *
     * @return possible object is
     * {@link Person }
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     *
     * @param value allowed object is
     *              {@link Person }
     */
    public void setPerson(Person value) {
        this.person = value;
    }

}
