//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 04:33:23 PM CET 
//


package org.bp.accountsubscribing;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.bp package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BookMovieSubscription_QNAME = new QName("http://accountsubscribing.bp.org/", "bookMovieSubscription");
    private final static QName _BookMovieSubscriptionResponse_QNAME = new QName("http://accountsubscribing.bp.org/", "bookMovieSubscriptionResponse");
    private final static QName _CancelBooking_QNAME = new QName("http://accountsubscribing.bp.org/", "cancelBooking");
    private final static QName _CancelBookingResponse_QNAME = new QName("http://accountsubscribing.bp.org/", "cancelBookingResponse");
    private final static QName _Fault_QNAME = new QName("http://accountsubscribing.bp.org/", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bp
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookMovieSubscription }
     */
    public BookMovieSubscription createBookMovieSubscription() {
        return new BookMovieSubscription();
    }

    /**
     * Create an instance of {@link BookMovieSubscriptionResponse }
     */
    public BookMovieSubscriptionResponse createBookMovieSubscriptionResponse() {
        return new BookMovieSubscriptionResponse();
    }

    /**
     * Create an instance of {@link CancelBooking }
     */
    public CancelBooking createCancelBooking() {
        return new CancelBooking();
    }

    /**
     * Create an instance of {@link CancelBookingResponse }
     */
    public CancelBookingResponse createCancelBookingResponse() {
        return new CancelBookingResponse();
    }

    /**
     * Create an instance of {@link Fault }
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link SubscribingInfo }
     */
    public SubscribingInfo createSubscribingInfo() {
        return new SubscribingInfo();
    }

    /**
     * Create an instance of {@link MovieSubscriptionAccount }
     */
    public MovieSubscriptionAccount createMovieSubscriptionAccount() {
        return new MovieSubscriptionAccount();
    }

    /**
     * Create an instance of {@link MovieSubscription }
     */
    public MovieSubscription createMovieSubscription() {
        return new MovieSubscription();
    }

    /**
     * Create an instance of {@link Person }
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookMovieSubscription }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BookMovieSubscription }{@code >}
     */
    @XmlElementDecl(namespace = "http://accountsubscribing.bp.org/", name = "bookMovieSubscription")
    public JAXBElement<BookMovieSubscription> createBookMovieSubscription(BookMovieSubscription value) {
        return new JAXBElement<BookMovieSubscription>(_BookMovieSubscription_QNAME, BookMovieSubscription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookMovieSubscriptionResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BookMovieSubscriptionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://accountsubscribing.bp.org/", name = "bookMovieSubscriptionResponse")
    public JAXBElement<BookMovieSubscriptionResponse> createBookMovieSubscriptionResponse(BookMovieSubscriptionResponse value) {
        return new JAXBElement<BookMovieSubscriptionResponse>(_BookMovieSubscriptionResponse_QNAME, BookMovieSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     */
    @XmlElementDecl(namespace = "http://accountsubscribing.bp.org/", name = "cancelBooking")
    public JAXBElement<CancelBooking> createCancelBooking(CancelBooking value) {
        return new JAXBElement<CancelBooking>(_CancelBooking_QNAME, CancelBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://accountsubscribing.bp.org/", name = "cancelBookingResponse")
    public JAXBElement<CancelBookingResponse> createCancelBookingResponse(CancelBookingResponse value) {
        return new JAXBElement<CancelBookingResponse>(_CancelBookingResponse_QNAME, CancelBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     */
    @XmlElementDecl(namespace = "http://accountsubscribing.bp.org/", name = "Fault")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, Fault.class, null, value);
    }

}
