//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 04:33:23 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://accountsubscribing.bp.org/")
package org.bp.accountsubscribing;
